/* 基础件的统一出口：调用方从 `@/components/base` 引入，不逐个深入 `components/base/<名>`。
   这里只做再导出，不带任何逻辑（见 architecture/03-boundaries.md §3）。 */

export { AlertDialog } from './alert-dialog'
export type { AlertDialogProps } from './alert-dialog'
export { BrandMark } from './brand-mark'
export type { BrandMarkProps, BrandId } from './brand-mark'
export { Button } from './button'
export type { ButtonProps } from './button'
export { CaptchaField } from './captcha-field'
export type { CaptchaFieldProps } from './captcha-field'
export { Checkbox } from './checkbox'
export type { CheckboxProps } from './checkbox'
export { DialogPage, DialogParts } from './dialog'
export type { DialogProps, DialogSize } from './dialog'
export { Drawer } from './drawer'
export type { DrawerProps } from './drawer'
export { Icon } from './icon'
export type { IconProps, IconSize } from './icon'
export { Input } from './input'
export type { InputProps } from './input'
export { Link } from './link'
export type { LinkProps, LinkState } from './link'
export { OtpField } from './otp-field'
export type { OtpFieldProps } from './otp-field'
export { Select } from './select'
export type { SelectGroup, SelectOption, SelectProps } from './select'
export { SegmentedControl } from './segmented-control'
export type { SegmentedControlProps, SegmentedOption } from './segmented-control'
export { Spinner } from './spinner'
export { TurnstileField } from './turnstile-field'
export type { TurnstileFieldProps } from './turnstile-field'
