name: Build | Release

on:
      push:
            branches:
                  - main
            paths-ignore:
                  - README.md
                  - LICENSE

jobs:
      Build:
            runs-on: ubuntu-latest
            steps:
                  - name: Checkout Repo
                    uses: actions/checkout@master

                  - name: Setup Node.js
                    uses: actions/setup-node@v3
                    with:
                          node-version: 18

                  - name: Setup Pnpm
                    uses: pnpm/action-setup@v2
                    with:
                          version: latest
                          run_install: false

                  - name: Get pnpm store directory
                    id: pnpm-cache
                    shell: bash
                    run: |
                          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

                  - uses: actions/cache@v3
                    name: Setup pnpm cache
                    with:
                          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
                          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
                          restore-keys: |
                                ${{ runner.os }}-pnpm-store-

                  - name: Install
                    run: pnpm install

                  - name: Test Build
                    run: npm run build --filter=xgen

                  - name: Upload Artifact
                    uses: actions/upload-artifact@v3
                    if: "contains(github.event.head_commit.message, '[release]')"
                    with:
                          name: xgen_dist
                          path: packages/xgen/dist

      Release:
            runs-on: ubuntu-latest
            if: "contains(github.event.head_commit.message, '[release]')"
            steps:
                  - name: Checkout
                    uses: actions/checkout@master

                  - name: Download Artifact
                    uses: actions/download-artifact@v3
                    with:
                          name: xgen_dist
                          path: xgen_dist

                  - name: Release
                    uses: softprops/action-gh-release@v1
                    with:
                          files: xgen_dist
                          body_path: CHANGELOG.md
