name: Release

on:
      push:
            tags:
                  - 'v*.*.*'

jobs:
      Build:
            runs-on: ubuntu-latest
            steps:
                  - name: Checkout Repo
                    uses: actions/checkout@master

                  - name: Download Artifact
                    uses: actions/download-artifact@v3
                    with:
                          name: release_xgen

                  - name: Release
                    uses: softprops/action-gh-release@v1
                    with:
                          files: release_xgen.tgz
                          body_path: CHANGELOG.md
